"""
    słownik który zawiera tłumaczenia angieslkich nazw pogody na polski
"""

weather_descriptions_translations = {
    'clear sky': 'bezchmurnie',
    'few clouds': 'mało chmur',
    'scattered clouds': 'rozproszone chmury',
    'broken clouds': 'duże chmury',
    'shower rain': 'przelotny deszcz',
    'rain': 'deszcz',
    'thunderstorm': 'burza',
    'snow': 'śnieg',
    'mist': 'mgła',
    'thunderstorm with light rain': 'burza z deszczem',
    'thunderstorm with rain': 'burza z deszczem',
    'thunderstorm with heavy rain': 'burza z deszczem',
    'light thunderstorm': 'lekka burza',
    'heavy thunderstorm': 'silna burza',
    'ragged thunderstorm': 'szarpana burza',
    'thunderstorm with light drizzle': 'burza z mżawką',
    'thunderstorm with drizzle': 'burza z mżawką',
    'thunderstorm with heavy drizzle': 'burza z mżawką',
    'light intensity drizzle': 'lekka mżawka',
    'drizzle': 'mżawka',
    'heavy intensity drizzle': 'silna mżawka',
    'light intensity drizzle rain': 'deszcz z mżawką',
    'drizzle rain': 'deszcz z mżawką',
    'heavy intensity drizzle rain': 'deszcz z mżawką',
    'shower rain and drizzle': 'deszcz z mżawką',
    'heavy shower rain and drizzle': 'deszcz z mżawką',
    'shower drizzle': 'mżawka',
    'light rain': 'lekki deszcz',
    'moderate rain': 'umiarkowany deszcz',
    'heavy intensity rain': 'silny deszcz',
    'very heavy rain': 'ulewny deszcz',
    'extreme rain': 'skrajny deszcz',
    'freezing rain': 'marznący deszcz',
    'light intensity shower rain': 'przelotny deszcz',
    'heavy intensity shower rain': 'przelotny deszcz',
    'ragged shower rain': 'szarpany deszcz',
    'light snow': 'lekki śnieg',
    'heavy snow': 'silny śnieg',
    'sleet': 'deszcz ze śniegiem',
    'light shower sleet': 'przelotny śnieg',
    'shower sleet': 'przelotny śnieg',
    'light rain and snow': 'deszcz ze śniegiem',
    'rain and snow': 'deszcz ze śniegiem',
    'light shower snow': 'przelotny śnieg',
    'shower snow': 'przelotny śnieg',
    'heavy shower snow': 'silny śnieg',
    'smoke': 'dym',
    'haze': 'mgła',
    'sand/dust whirls': 'pył',
    'fog': 'mgła',
    'sand': 'piasek',
    'dust': 'pył',
    'volcanic ash': 'popiół',
    'squalls': 'szkwały',
    'tornado': 'tornado',
    'few clouds: 11-25%': 'mało chmur',
    'scattered clouds: 25-50%': 'rozproszone chmury',
    'broken clouds: 51-84%': 'duże chmury',
    'overcast clouds: 85-100%': 'zachmurzenie',
    'overcast clouds': 'zachmurzenie'
}
